/**
 * @generated by Agentway tokens:build
 * TypeScript Design Token Definitions
 */

export type PrimaryColorShade = 50 | 100 | 500 | 600 | 700 | 900;
export type SpacingToken = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
export type RadiusToken = 'sm' | 'md' | 'lg' | 'full';
export type SurfaceLevel = 'ground' | 'base' | 'elevated' | 'highest';
export type ThemeMode = 'light' | 'dark';

export interface DesignTokens {
  theme: ThemeMode;
  colors: Record<string, string | Record<string, string>>;
  spacing: Record<SpacingToken, string>;
  radius: Record<RadiusToken, string>;
}
